"""create initial tables

Revision ID: 4c0d030ef992
Revises: 
Create Date: 2025-12-16 03:48:46.050649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0d030ef992'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('main_region', sa.String(length=100), nullable=False),
    sa.Column('formatted_address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geocode_source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_formatted_address'), 'areas', ['formatted_address'], unique=False)
    op.create_index(op.f('ix_areas_latitude'), 'areas', ['latitude'], unique=False)
    op.create_index(op.f('ix_areas_longitude'), 'areas', ['longitude'], unique=False)
    op.create_index(op.f('ix_areas_normalized_name'), 'areas', ['normalized_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CLINIC', 'WELFARE', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('formatted_address', sa.String(length=255), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geocode_source', sa.String(length=32), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_area_id'), 'clinics', ['area_id'], unique=False)
    op.create_index(op.f('ix_clinics_formatted_address'), 'clinics', ['formatted_address'], unique=False)
    op.create_index(op.f('ix_clinics_latitude'), 'clinics', ['latitude'], unique=False)
    op.create_index(op.f('ix_clinics_longitude'), 'clinics', ['longitude'], unique=False)
    op.create_index(op.f('ix_clinics_name'), 'clinics', ['name'], unique=False)
    op.create_index(op.f('ix_clinics_owner_id'), 'clinics', ['owner_id'], unique=False)
    op.create_table('clinic_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_images_clinic_id'), 'clinic_images', ['clinic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinic_images_clinic_id'), table_name='clinic_images')
    op.drop_table('clinic_images')
    op.drop_index(op.f('ix_clinics_owner_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_name'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_longitude'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_latitude'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_formatted_address'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_area_id'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_areas_normalized_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_longitude'), table_name='areas')
    op.drop_index(op.f('ix_areas_latitude'), table_name='areas')
    op.drop_index(op.f('ix_areas_formatted_address'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
